#define normalsearch 5
#define convertworksheet 6
#define similaritysearch 7
#define ChemDrawFunctions 8
#define Rgroupanalysis 10
#define creatinganexperiment 11
#define moleculeproperties 12
#define settingpreferences 13
#define Exporttables 33
#define Importhitlist 34
#define importtables 29
#define preferences 14
#define whatsnew 4
#define savingstructures 15
#define searching 16
#define synchronizingtables 17
#define workingwithstrucutres 18
#define combichem 19
#define configuringplates 20
#define addingstructures 21
#define displayingstructures 22
#define renamingstructures 23
#define gettingstarted 24
#define Usinghelp 9
#define Gettingstarted 3
#define Shortcutsandhotkeys 2
#define Contents 0
#define searchingreactants 25
#define browsingplates 26
